### ISSUE TITLE
Cant remove or add scripts

### ISSUE THREAD

**Issue by Kalle801** [DunkoUK/dunko_vrp#103]
Good Day. It seems like: deleting/adding Scripts to the Server.cfg has no effect.
Is there any trick?

**Comment by MM1212** [comment]
If youre on zap, disable the autoupdate and the force overwrite options in the resources panel; for further support, use the official dunkos discord!

**Comment by Kalle801** [comment]
May i ask for the Discord link? :)

**Comment by MM1212** [comment]
https://discord.gg/J3CsZd
