### ISSUE TITLE
Not full admin  menu

### ISSUE THREAD

**Issue by StefanROM** [DunkoUK/dunko_vrp#110]
Hi, when i got full vrp server i had all functions in admin menu, but today i see as i do not have spawnveh, tptowaypoint and more, please help , thanks!

**Comment by zThundy** [comment]
check your perms and also... those functions are built in an extension called vrp_basic_menu

**Comment by JoeMayes** [comment]
If u need more help join the discord @ https://discord.gg/jcf3QM4vrt
