### ISSUE TITLE
Save damage in garage.

### ISSUE THREAD

**Issue by Kongen2110** [DunkoUK/dunko_vrp#111]
Hey, Is there any way it is possible to save the car damage when you park the car in the garage?

**Comment by zThundy** [comment]
for how vrp is made, it can be preatty hard to do that. instead you can check if a vehicle is damaged or not using the FiveM function IsVehicleDamaged

https://runtime.fivem.net/doc/natives/#_0xBCDC5017D3CE1E9E

**Comment by JamesEU** [comment]
Also, this is a feature, not an issue please ask one of our resource developers to make this as a suggestion.

**Comment by JoeMayes** [comment]
If u need more help join the discord @ https://discord.gg/jcf3QM4vrt
