### ISSUE TITLE
Spawn car more than one time

### ISSUE THREAD

**Issue by ZermanGR** [DunkoUK/dunko_vrp#112]
how to spawn more of the same types of vehicle but not the same model?

**Comment by JamesEU** [comment]
Hi, you can modify this here
![pic for help](https://user-images.githubusercontent.com/60899490/103390159-c9a93d80-4b0a-11eb-93d9-74164fdf870f.png)

**Comment by JamesEU** [comment]
Delete these lines and you'll be able to do so.

**Comment by JoeMayes** [comment]
If u need more help join the discord @ https://discord.gg/jcf3QM4vrt
