### ISSUE TITLE
static menu for display things

### ISSUE THREAD

**Issue by zThundy** [DunkoUK/dunko_vrp#113]
Hello guys. I have a question: i recently made a societies script for vrp that can let you update the paycheck of each rank. I was wondering if is there a way to create a sub-menu inside the society menù (that i have already built) to show just the paycheck of that rank:

example:
Captain: 2000
Liutenent: 1000
ecc....

without any function triggered on click.

**Comment by JamesEU** [comment]
Hi, this is not an issue with the framework please use our support channels next time.

**Comment by JoeMayes** [comment]
If u need more help join the discord @ https://discord.gg/jcf3QM4vrt
