### ISSUE TITLE
No static IDs when connecting

### ISSUE THREAD

**Issue by Yeagorn** [DunkoUK/dunko_vrp#114]
Hello! If I connect I get id 1, after that I connect again I got id 2 but I want them static like for 1 guy with steam and R* id 1 another guy steam and R* id 2 how to do so?

**Comment by BadeDk** [comment]
That is how the pack is made. It shows session id and not DB id, you need to find a resource that show DB id and not session ID.

**Comment by BadeDk** [comment]
Join the discord discord.gg/44TtfK6 if you have other issus

**Comment by JoeMayes** [comment]
If u need more help join the discord @ https://discord.gg/jcf3QM4vrt
