### ISSUE TITLE
Identification Error please!!! Urgent

### ISSUE THREAD

**Issue by measlystorm7808** [DunkoUK/dunko_vrp#115]
Hello there! I need ur help please! I tried several things and cant get rid of that id error. Its driving me nuts mate. I have have it like in pictures, but nothing works tried both local and 127.0.0.1 but same thing happens...

![Screenshot_1](https://user-images.githubusercontent.com/56112629/70325564-454d9380-1800-11ea-9ff1-56ba1a4ca719.png)

![Screenshot_2](https://user-images.githubusercontent.com/56112629/70325569-47afed80-1800-11ea-8ace-2eb3de2e0389.png)

measlystorm#2351 Add me directly if u want to help me there.

Thank you for any response u give.

**Comment by BadeDk** [comment]
You need to join the discord to get more help with that. there is few things that will need to be check.
discord.gg/44TtfK6

**Comment by measlystorm7808** [comment]
Cant u tell me here please?

**Comment by measlystorm7808** [comment]
No thanks no one helped.

**Comment by BadeDk** [comment]
That is not truth i tried to help you! But in the end you did not follow the discord rules. So i am sorry but we cant help you in this matter more then we allready did. Have a nice day.

**Comment by measlystorm7808** [comment]
Ok thanks sorry. Thank you I have managed to sort it now anyways.

**Comment by JoeMayes** [comment]
If u need more help join the discord @ https://discord.gg/jcf3QM4vrt
