### ISSUE TITLE
No Player Model or Ability to move around

### ISSUE THREAD

**Issue by MiddleSkillz** [DunkoUK/dunko_vrp#116]
I installed it but when i load into game i don't have a player model, im invisible and a cannot move around

**Comment by BadeDk** [comment]
Its normal to load in and dont have a player model and cant move on the start until vrp has loaded all.
But for more help on your problem join the discord kAfBuJG and provide a ful log of your consol.

**Comment by MiddleSkillz** [comment]
i joined the discord and also i've been in for 5 minutes and still nothing

**Comment by justinfarmer14** [comment]
Did you attempt to reach out to our support team with your log file?

**Comment by MiddleSkillz** [comment]
I've sorted out the problem
