### ISSUE TITLE
fetching info from server fail

### ISSUE THREAD

**Issue by DerKieler91** [DunkoUK/dunko_vrp#118]
Hello, 

I Become to Join this Error: 
fetching info from server fail

who i can fix this? :D

**Comment by iWanheda** [comment]
Correct IP/Port?

**Comment by DerKieler91** [comment]
Yes other game mode works

**Comment by iWanheda** [comment]
Localhost? VPS? Gameserver? Dedi?

**Comment by DerKieler91** [comment]
Win VPS

**Comment by iWanheda** [comment]
Make sure your firewall is not blocking the port, and check IP + Port

**Comment by DerKieler91** [comment]
All ok. 

Everything is fine now.

But now I get the following error: Cannot load resource fivem

**Comment by iWanheda** [comment]
Your 'fivem' resource is missing data in `__resource.lua` or you fucked up.

**Comment by JoeMayes** [comment]
If u need more help join the discord @ https://discord.gg/jcf3QM4vrt
