### ISSUE TITLE
Chat Identity Issue

### ISSUE THREAD

**Issue by Tokolosh** [DunkoUK/dunko_vrp#119]
When talking in chat it is using the Steam Name instead of the In Character Identity. Shouldnt this only be so if using OOC Chat?

I seem to have this problem with normal chat as well as /me

**Comment by JamesEU** [comment]
A custom chat is not included with this resource please only open issues related to the framework.

**Comment by JoeMayes** [comment]
If u need more help join the discord @ https://discord.gg/jcf3QM4vrt
