### ISSUE TITLE
[vRP] identification Error

### ISSUE THREAD

**Issue by Rafaeloking** [DunkoUK/dunko_vrp#120]
I am trying to enter a server in Fivem and it keeps telling me: [vRP] identification Error. I tried deleting the cache multiple times but I was unsuccessful in my attempt to join the server. Could anyone try to help me? I will tell you more details if necessary.

**Comment by zMasterAle** [comment]
This is an error related to the database, check if your db connection is good, username, password, db name...

**Comment by Ahmedegt441** [comment]
> This is an error related to the database, check if your db connection is good, username, password, db name...

please can fix my issue ? i create it today ( i cant download Dunko vrp and file size is unknown)

**Comment by pooriamm** [comment]
where is the db files to import?

**Comment by JamesEU** [comment]
They are created automatically.

**Comment by JoeMayes** [comment]
If u need more help join the discord @ https://discord.gg/jcf3QM4vrt

**Comment by JoeMayes** [comment]
If u need more help join the discord @ https://discord.gg/jcf3QM4vrt
