### ISSUE TITLE
the size of  dunko_vrp is unknown and i tried too many to download but i cant

### ISSUE THREAD

**Issue by Ahmedegt441** [DunkoUK/dunko_vrp#122]
![image](https://user-images.githubusercontent.com/65295323/81948116-0cfd7d00-960a-11ea-9a81-87b3d9ed70e3.png)

![image](https://user-images.githubusercontent.com/65295323/81948154-18e93f00-960a-11ea-8f7c-87ac609ff845.png)

please upate the files or upload it again
please

**Comment by Ahmedegt441** [comment]
hello ?

**Comment by pooriamm** [comment]
not really an issue

**Comment by JoeMayes** [comment]
If u need more help join the discord @ https://discord.gg/jcf3QM4vrt
