### ISSUE TITLE
Street names on top of mini map

### ISSUE THREAD

**Issue by alherrera13** [DunkoUK/dunko_vrp#123]
Hi, I need to remove the streets names over the minimap, I searched for the call function but I don't found. Can you say me where is to deactivate? Tks.

**Comment by Sethyyyy** [comment]
its in CustomScripts

**Comment by JamesEU** [comment]
The issue has been answered even though this did not need to become an issue next time use our support channels.

**Comment by JoeMayes** [comment]
If u need more help join the discord @ https://discord.gg/jcf3QM4vrt
