### ISSUE TITLE
Railhouse problem

### ISSUE THREAD

**Issue by alamri55** [DunkoUK/dunko_vrp#125]
How to solve this problem
Attached is a picture for clarification
![7fb5e6b6e8521be4](https://user-images.githubusercontent.com/37021225/87364774-2de83d00-c57d-11ea-904a-02daeb7cec27.png)

**Comment by Dynamic-eGc** [comment]
Make sure you clear your cache folder, If you had done already. Look at the ymap and make sure its all set up properly.

Kind Regards
Dynamic
Dunko vRP Support Team

**Comment by JoeMayes** [comment]
If u need more help join the discord @ https://discord.gg/jcf3QM4vrt
