### ISSUE TITLE
What is the name in the files of the hud cuz i wanna modify it

### ISSUE THREAD

**Issue by GixBlue** [DunkoUK/dunko_vrp#127]

**Comment by JuiceRO2k** [comment]
Hey . If u are talking abt the corner one. Where the job and money are, is simple : 

Money - vrp/cfg/money.lua line 8 i believe .

Job - vrp_job_display/cfg/display.lua line 4 

Both lines have at begining ( where the hud is made this "cfg.display_css = [[" )

**Comment by JamesEU** [comment]
This does not need to become an issue on GitHub please use our support channel for this next time.

**Comment by JoeMayes** [comment]
If u need more help join the discord @ https://discord.gg/jcf3QM4vrt
