### ISSUE TITLE
Jobs not working

### ISSUE THREAD

**Issue by rusk1y11** [DunkoUK/dunko_vrp#128]
I need help with jobs. I go to the police station and walk over to the markers and there is no popup, and on other jobs, like mechanic it says im missing repairkit and for a garbage job it says im missing garbage or something like that. Please help!!

**Comment by bluefir111** [comment]
Hi,
Police jobs are white listed jobs you have to go k>admin>add group> USER ID> cop  then you should be able to activate those markers.

As for the mechanic job you need to go to the mechanics garage/market shop to get repair kits. its located in the impound lot that ur car gets taken to when you get arrested in GTA online. Same goes for the Garbage job.  look in the VRP/group.lua or VRP/markets.lua files for locations for these places. Also join the discord server for dunkovrp as you can get faster responses there.
