### ISSUE TITLE
Phone/Ui not allowing selection

### ISSUE THREAD

**Issue by majestic-owl** [DunkoUK/dunko_vrp#129]
at times when accessing the options within the phone/ui, the phone freezes and will not allow anyone on the server to press enter and select something such as purchasing a vehicle or selecting inventory. Sometimes the phone even gets stuck out completely forcing you to disconnect which solves the stuck phone problem but still won't let you make a selection. Plz help ps haven't messed with any scripts or added any mods, so I'm going out on a limb saying maybe it' just a server connection issue but everything else has worked fine so far...

**Comment by EqualizerNetwork** [comment]
If you phone UI is slow response time this could be a edit you have done, Revert back to the OG vrp folder and add your edits in till you get the same error then you know what is causing it. But sometime UI/Phone response time etc is due to database.

Kind Regads,
Dynamic
