### ISSUE TITLE
error task_god

### ISSUE THREAD

**Issue by XxTopKillerzZ** [DunkoUK/dunko_vrp#13]
Hi,

i get this error in console:

Error resuming coroutine: modules/admin.lua:406: attempt to call a nil value (field 'getUsersByPermission')
stack traceback:
        modules/admin.lua:406: in function 'task_god'

I think its because my grouop.lua file but i cant figure out where is the problem

My file:https://hastebin.com/ayefitayun.lua

Tanks,
TopKiller

**Comment by DunkoUK** [comment]
Line 428 "cop.whitelisted", - you need to remove the comma
