### ISSUE TITLE
[vRP] Identification error

### ISSUE THREAD

**Issue by Andrea-98** [DunkoUK/dunko_vrp#130]
Hi, I just installed DunkoRP on my PC and when I try to join the server by Local Host it shows up: [vRP] Identification error.
The database in use is that of essentialmode as I am doing a data migration regarding the server management and I am trying to integrate their features, I use their tables and integrate the missing ones, of course I have already configured xampp and the configuration files of vRP (vrp / cfg / base - ip address and database name) and (vrp / base - mysql queries) for the database.
How can I solve the problem?

![Fivem](https://user-images.githubusercontent.com/15652621/99648793-b8710980-2a53-11eb-9b33-9ffde677bd99.PNG)
![Server](https://user-images.githubusercontent.com/15652621/99648796-bad36380-2a53-11eb-8bdf-fba112a92a21.PNG)

**Comment by kalinzange** [comment]
Not an issue, you're put the wrong credentials in server.cfg or base.lua

**Comment by Andrea-98** [comment]
This is how the credentials are configured

![base](https://user-images.githubusercontent.com/15652621/99657428-71d4dc80-2a5e-11eb-9d7c-a25dc98e737d.PNG)
![server](https://user-images.githubusercontent.com/15652621/99657440-739ea000-2a5e-11eb-8f9a-a6fe5b71a76e.PNG)

**Comment by kalinzange** [comment]
Why are you using an ESX DB to try and connect to a VRP one?

Try make a new DB and change that. Let me know how it goes

**Comment by kalinzange** [comment]
Also:

`The database in use is that of essentialmode as I am doing a data migration regarding the server management and I am trying to integrate their features, I use their tables and integrate the missing ones`

This is not VRPEX, unfortunately. It's not really recommend for you to try use Missing tables or use both frameworks at one DB it will be a completely mess, if you want to migrate data, you can export the SQL ESX Database, make a new sql file and copy the data to the new vRP, however you will need to change how the data is storage, vrp is just different.

**Comment by Andrea-98** [comment]
I am forced to perform a migration as mentioned before because I have no possibility to leave the server off for too long. Before performing the actual migration I am doing some tests locally. For speed, I preferred to use queries that searched for data within the existing DB since the DB engine and the characters of the tables are the same. what do you mean by "you will have to change the way the data is stored"?

![conf](https://user-images.githubusercontent.com/15652621/99660747-148f5a00-2a63-11eb-8593-2e018eca0426.PNG)

**Comment by Andrea-98** [comment]
in the end, many data are linked through foreign keys between the various tables of the DB

**Comment by kalinzange** [comment]
> what do you mean by "you will have to change the way the data is stored"?

If I'm not mistaken ESX uses data per table:
(Example):
![image](https://user-images.githubusercontent.com/38161086/99662909-cb88d700-2a5d-11eb-9de9-292b27895815.png)

Meanwhile in vrp in-game user's data is data per comma:
![image2](https://user-images.githubusercontent.com/38161086/99663974-5cac7d80-2a5f-11eb-8efc-0031846e8fe0.png)

**Comment by Andrea-98** [comment]
so I should take all the essentialmode (user, job, Inventory etc..). tables and rewrite the individual dvalues ​​for each game PG by hand?

**Comment by Andrea-98** [comment]
is there a possibility at the moment of resolving the identification error keeping the tables and without having to rewrite everything and possibly self-develop a script that does the convention and allows you to use the same tables?

**Comment by kalinzange** [comment]
> so I should take all the essentialmode (user, job, Inventory etc..). tables and rewrite the individual dvalues ​​for each game PG by hand?

I'm not sure how you will proceed and a best way, I just wanted to tell you there's difference between VRP and ESX and what can cause system issues during migration.

**Comment by Andrea-98** [comment]
Of course I am aware that they are different and I thank you for the support you are giving me. If there was a way at the time of solving the identification error it would be great, for the data I will have to study a method something that writes me the values ​​of ESX in dvalue for vRP but at the same time that the values ​​of dvalue of vRP are written in ESX tables for easier identification and integration of custom scripts

**Comment by JoeMayes** [comment]
@Andrea-98 Just to say we do have a discord where we can give support there as well @ discord.gg/

**Comment by JoeMayes** [comment]
Discord
If you need help, head over to my Discord: https://discord.gg/kAfBuJG

**Comment by Andrea-98** [comment]
the error described above also occurs when using the vRP tables and only vRP with related addons
