### ISSUE TITLE
Didn't start some resources

### ISSUE THREAD

**Issue by nvybvl** [DunkoUK/dunko_vrp#136]
Couldn't find resource blips.
Couldn't find resource club_B.
Couldn't find resource club_R.
Couldn't find resource racetrack.

How can we fix those ?

**Comment by P4NDAzzGaming** [comment]
You're simply missing the resources.. somehow.

**Comment by nvybvl** [comment]
They doesn't exist.

**Comment by arthur-rl** [comment]
Wanna know how to fix them. You should probably add them to your resources folder. Its basic common sense

**Comment by nvybvl** [comment]
No bro. What I want to say its the following:
Classic SFX Data doesnt contain any blips folder or club b&r or racetrack.
Also Dunko VRP .zip doesn't contain them.

My question is why they are called in server.cfg if they doesn't exist ?

**Comment by arthur-rl** [comment]
Maybe cause they used to exist. Just remove them from your server.cfg duh

**Comment by nvybvl** [comment]
> Maybe cause they used to exist. Just remove them from your server.cfg duh

lol, yes. that's what I did but Dunko dev's have to edit their git also

**Comment by arthur-rl** [comment]
Then why are you making an issue? 
Make a PR to remove them.

**Comment by kalinzange** [comment]
https://github.com/DunkoUK/dunko_vrp/pull/132

The resources no longer exist. Remove from server.cfg
Feel free to make a PR regarding it.
