### ISSUE TITLE
Fetching info from server attempt 3

### ISSUE THREAD

**Issue by Fledrousek** [DunkoUK/dunko_vrp#139]
Hi, i have same problem, i have Win VPS and no one can connect to the server because it writes fetching info from server attempt 3 | please help me...

**Comment by kalinzange** [comment]
Open your FiveM Ports in Firewall

**Comment by JamesEU** [comment]
This is not an issue relating to the framework please close this issue.

**Comment by JoKeRxTD** [comment]
Issue Closed
