### ISSUE TITLE
stuck at awaiting scripts

### ISSUE THREAD

**Issue by xView60** [DunkoUK/dunko_vrp#154]

**Comment by JamesEU** [comment]
This is not an issue with the framework you've forgotten to install the FiveM base resources as instructed to do so within the instructions.

**Comment by JamesEU** [comment]
Please close the issue and ask for support within the Discord channels.

Many Thanks, 

JamesUK

**Comment by JoeMayes** [comment]
Dunko's Community RP Discord
https://discord.gg/QQGDpbuyd5
