### ISSUE TITLE
Multiple Issues with VRP and need help!

### ISSUE THREAD

**Issue by tallahassee33** [DunkoUK/dunko_vrp#161]
So We added Dunkos Vrp to our server and it launched and started great, but then the following issues accured
. EUP Vest started to disappear off our characters
. The respawn feature is broken (Is it possible to disable it.)
. We cant give money or do things related to it because I get a "No Player Near By error) Mpay and Mcharge do work!
Thats about all the issues we have. If some one can help that would be great!

**Comment by kalinzange** [comment]
> . EUP Vest started to disappear off our characters
Not a VRP Issue

> The respawn feature is broken (Is it possible to disable it.)
Screenshot? What have you done to make it broken, additional info needed

> . We cant give money or do things related to it because I get a "No Player Near By error) Mpay and Mcharge do work!
What you mean with give money, are you trying get from K > Admin? Do you use a separate resource? Additional Info needed

**Comment by tallahassee33** [comment]
So for Vest Ill get it looked at.
For respawn we just want to disable it honestly if possible (We havent messed any respawn scripts)
https://imgur.com/a/CacP5wv
^^^^^^^^^^^^^^^^^^^^
That link is to the screenshot!
The bottom left towards on top of the mini map it says no players near by. 
Thats when i try doing any interactions with others in game

**Comment by tallahassee33** [comment]
Need anything else?

**Comment by tallahassee33** [comment]
Do you need more screen shots?

**Comment by tallahassee33** [comment]
Anyfix?

**Comment by kalinzange** [comment]
Why are you running a FivePD + vRP server?

**Comment by JamesEU** [comment]
> We cant give money or do things related to it because I get a "No Player Near By error) Mpay and Mcharge do work!

I'll investigate this issue but the other issues aren't related to us. The respawn does work as I dev on a default dunko server a lot and die so I wait 5 minutes and I'm respawned.

**Comment by tallahassee33** [comment]
> > We cant give money or do things related to it because I get a "No Player Near By error) Mpay and Mcharge do work!
> 
> I'll investigate this issue but the other issues aren't related to us. The respawn does work as I dev on a default dunko server a lot and die so I wait 5 minutes and I'm respawned.

Alright that sounds good Ima remove Fivepd and re-add vrp and get it set up properly. 
Can The revive script be disabled or?

**Comment by JamesEU** [comment]
The revive script can be disabled yeah.

**Comment by tallahassee33** [comment]
> The revive script can be disabled yeah.

How can I do that if you dont mind telling me?

**Comment by JamesEU** [comment]
I'm going to do a commit shortly, so you can easily disable these from the configuration files.

**Comment by tallahassee33** [comment]
Yeah wait the when add some thing from boday armour and accsesories to your player it dissapears

**Comment by tallahassee33** [comment]
I stopped all vrp files to see if it was us, when we enable it the vest starting doing the dissapear thing

**Comment by JamesEU** [comment]
> I stopped all vrp files to see if it was us, when we enable it the vest starting doing the dissapear thing

This is still not our issue sorry.

**Comment by kevingame895** [comment]
try to have a look at this. 
https://forum.cfx.re/t/bulletproof-vest-bug/93595/10?u=c9mm

**Comment by JamesEU** [comment]
> try to have a look at this.
> https://forum.cfx.re/t/bulletproof-vest-bug/93595/10?u=c9mm

Ah, apologies I'll likely just fix this

**Comment by tallahassee33** [comment]
> > try to have a look at this.
> > https://forum.cfx.re/t/bulletproof-vest-bug/93595/10?u=c9mm
> 
> Ah, apologies I'll likely just fix this

Dont get what they want me to do?
Do they want me to delete that peace of code or?

**Comment by kevingame895** [comment]
comment it and it should work!
comment it and it should work!
comment it and it should work!
comment it and it should work!
comment it and it should work!
comment it and it should work!
comment it and it should work!
shit my bad keyboard fucked

**Comment by JamesEU** [comment]
Yeah remove that line of code

**Comment by tallahassee33** [comment]
Ok great! 
The only issue i have is that "No Near By Players" when you try to give money, Ask ID, loot body and etc

**Comment by tallahassee33** [comment]
> I'm going to do a commit shortly, so you can easily disable these from the configuration files.

Sorry if im asking to much, wheres would i find the revive script for vrp

**Comment by JamesEU** [comment]
> > I'm going to do a commit shortly, so you can easily disable these from the configuration files.
> 
> Sorry if im asking to much, wheres would i find the revive script for vrp

https://github.com/DunkoUK/dunko_vrp/pull/162/files

**Comment by JamesEU** [comment]
There is now a settings config in sharedcfg/options.lua for you to do this.

**Comment by JoeMayes** [comment]
Join The Dunkos Discord For More Support https://discord.gg/SxynFRfjuW
@JamesEU aka JamesUK#6793

**Comment by JoeMayes** [comment]
Join The Dunkos Discord For More Support https://discord.gg/SxynFRfjuW
@JamesEU aka JamesUK#6793
