### ISSUE TITLE
[BUG] Freeze player

### ISSUE THREAD

**Issue by luisflorido** [DunkoUK/dunko_vrp#17]
Hi, when some players join in server, they just stay frozen in spawn and cannot do anything (no errors on client log and server log), they are invisible and locked, i think is something released to identity because anything they do with requires identity say a error, this is fixed when i reboot server but affect others people after.

**Comment by DunkoUK** [comment]
Apologies I didn't notice this issue, I assume it's resolved as you've closed it?

**Comment by luisflorido** [comment]
Yes, it's fixed.

**Comment by DunkoUK** [comment]
Glad you fixed it mate.
