### ISSUE TITLE
ATM's cant withdraw or deposit money

### ISSUE THREAD

**Issue by Fury0101** [DunkoUK/dunko_vrp#173]
I am adding money to myself in cash through the admin menu but I can't deposit it at an atm. I also attempted to withdraw money and there was no change. Any way ti fix?

**Comment by JamesEU** [comment]
Likely because you may have one sync turned on incorrectly which may result in coordinate checks failing

**Comment by JamesEU** [comment]
There is a check if onesync is enabled or not but in the case you have it enabled incorrectly this is why it'd error.

**Comment by JamesEU** [comment]
You can find out how to use one sync correctly through https://forum.cfx.re/t/onesync-infinity-how-to-use-it/996612#:~:text=To%20use%20it%2C%20simply%20launch,hosting%20for%20the%20latest%20info. or alternatively visit the Dunko discord and we can help you further, however, this is not a problem with the framework and is a user error, however.
