### ISSUE TITLE
Unknown client

### ISSUE THREAD

**Issue by luisflorido** [DunkoUK/dunko_vrp#18]
When i try to use whitelist, and some players try to join server maybe he get this error, i've searching for a solution but i have not found nothing and not many posts about it.

**Comment by KilobaiD** [comment]
What kind of error are you talking about?

**Comment by luisflorido** [comment]
![gf3hl7sgtdevossyav9nza](https://user-images.githubusercontent.com/7344056/36317147-6c3cba18-1323-11e8-840e-05783de485cf.png)
just this in client, in server is normal, without errors, just the not whitelisted user, i've tried to start server with minimum resources but doesn't worked

**Comment by DunkoUK** [comment]
It means they aren't on the list, so they can't connect.

The whitelist resource is just a throw in, you can use vRP whitelist if you'd like.

Best way to use it, unwhitelist your server, let players join who you want to whitelist then K > Admin >Whitelist > Database ID

Restart and enable whitelist and you're on a winner.

To enable/disable go to vrp/cfg/base.lua - line 13 change to true/false.

Closing.

**Comment by luisflorido** [comment]
in some clients they show the whitelist message (in deferrals done) that shows their id so I can add it in the list, but is showing this error in most of cases

**Comment by DunkoUK** [comment]
As I said, if it's causing issues just use the built in vRP whitelist mate
