### ISSUE TITLE
How to add vrp_showroom to dunkso vrp

### ISSUE THREAD

**Issue by tallahassee33** [DunkoUK/dunko_vrp#187]
I have been trying to add Vrp_showroom to dunkos vrp. But no luck! Any help available?

**Comment by JamesEU** [comment]
Issues ARE not support requests. Nor is this an item related to the pack, please make an issue on the ORIGINAL repository.

**Comment by JoeMayes** [comment]
Discord
If you need help, head over to my Discord: https://discord.gg/kAfBuJG
