### ISSUE TITLE
@vrp/modules/money.lua attempt to index a nil value (global : vRPConfig)

### ISSUE THREAD

**Issue by FabianxddenisYT** [DunkoUK/dunko_vrp#199]

**Comment by JamesEU** [comment]
this is an issue from your end you do not have the correct version / missing files.

**Comment by JamesEU** [comment]
You are missing the sharedcfg/options.lua

**Comment by JamesEU** [comment]
Further information can be found from our support Discord https://discord.gg/2TsER7HNQw
