### ISSUE TITLE
not issues, but possible changes.

### ISSUE THREAD

**Issue by Pesoen** [DunkoUK/dunko_vrp#20]
in vrp/cfg/groups.lua
under user player.check is added twice, not sure if this is intentional.

in vrp/modules/money.lua
line 162 consider making wallet = math.floor(tmp.wallet) and bank = math.floor(tmp.bank)
to remove long numbers, and annoy players less.
line 170 consider making wallet = math.floor(v.wallet) and bank= math.floor(v.bank).
again, to remove long numbers.

Other than that, keep up the good work, love using this, but always have to add these things on my own/comment them out multiple times for the same user.

**Comment by DunkoUK** [comment]
Feel free to add it as a pull request mate

**Comment by Pesoen** [comment]
Pull request made, closing this one.
