### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by F1CUSS** [DunkoUK/dunko_vrp#210]
I have a zap hosting server and when i edit something in vrp folder resets when i restart the server. I work with filezilla

**Comment by JoeMayes** [comment]
Hello @F1CUSS.
U need to login to your zap hosting control panel and under plugins you will see next to vrp there is a option to turn on and off Force override you neeed to make sure that is off then restart your server.

Join the discord here @ https://discord.gg/kAfBuJG

**Comment by kalinzange** [comment]
Also GitHub Issues are not for support
