### ISSUE TITLE
Dirty_Money

### ISSUE THREAD

**Issue by vuhoangsje** [DunkoUK/dunko_vrp#246]
Hi, I have your VRP Edited, can I ask where is the place to wash money, is it visible on map or something?

**Comment by kalinzange** [comment]
Wash Money isn't added to the Dunko's Pack, there before there's no location.

**Comment by vuhoangsje** [comment]
> 
> 
> Wash Money isn't added to the Dunko's Pack, there before there's no location.

So i have to add that resource by my self, right ?

**Comment by kalinzange** [comment]
> > Wash Money isn't added to the Dunko's Pack, there before there's no location.
> 
> So i have to add that resource by my self, right ?

Yes.

@JamesEU Please close this
