### ISSUE TITLE
vRP.closeMenu is not working

### ISSUE THREAD

**Issue by LeFruJohn0** [DunkoUK/dunko_vrp#250]

**Comment by JamesEU** [comment]
However, these functions do work when used properly for example in the way loot bags work and how even the phone closes..

**Comment by JamesEU** [comment]
You can obtain support through our official support channels where we will assist you.

**Comment by LeFruJohn0** [comment]
Well Callum muted me because I telled him he behave like a "Discord Moderator" and then he muted with the reason : "Insulted a staff member"

**Comment by LeFruJohn0** [comment]
Now I reentered the discord server and I can't type ?agree because I am muted

**Comment by JamesEU** [comment]
Hi, please consult with the relevant staff member about this and if needed contact Kalin regarding any moderation issues.

**Comment by LeFruJohn0** [comment]
Ok, thank you

**Comment by JamesEU** [comment]
https://github.com/DunkoUK/dunko_vrp/blob/542f90c9da8efae0fda590ae21974fdfa0bde4a7/vrp/modules/sv_lootbags.lua#L190 

Examples of vRP.closeMenu can be found here

**Comment by Davidoff7776** [comment]
James you closed my issue too. But I have problems with every menu. After I walk away it still doesn't exit the menu.

**Comment by LeFruJohn0** [comment]
I have this problem to. And I didn't even touched the vrp

**Comment by JamesEU** [comment]
The issue is no one experiences this apart from you guys I do not even experience this on the default production build so without reproducibility I cannot assist.

**Comment by Davidoff7776** [comment]
@JamesEU can you share your server.cfg?

**Comment by JamesEU** [comment]
My server.cfg is just 

ensure ghmattimysql 
ensure vrp_mysql 
ensure vrp

**Comment by Davidoff7776** [comment]
@JamesEU try reproducing it with my server: https://github.com/Davidoff7776/frogland

**Comment by JamesEU** [comment]
I will attempt to shortly.

**Comment by Davidoff7776** [comment]
@JamesEU Have you had any success yet?
