### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by CzarZAR151** [DunkoUK/dunko_vrp#251]
I'm new to running servers for FiveM, and I decided to try out Zap-Hosting for making the server. After setting it up and making sure it actually works, I noticed some textures were missing for the clothes, faces, hair, and some other things and haven't been able to figure out why they won't show. I have an attached image below. Any idea how I can fix this?
![download (1)](https://user-images.githubusercontent.com/53183708/126858885-c4733fd9-6d1e-47bc-9ed8-c4ae56152fd0.jpeg)

**Comment by Caz-Developer** [comment]
This Looks More Like An Issue With Your EUP, ATM in vrp there are no texture index's for your skin colour, I'm working on a push for it but go to gender change and change to male and go from there, I might be wrong but that's most likely it

**Comment by CzarZAR151** [comment]
After changing to make and going through customizations, some come out as this too. Either missing completely, duplicate feature, or this checkered texture
![download (2)](https://user-images.githubusercontent.com/53183708/126878638-5774347f-bcd4-4b72-8cce-1f219936dc17.jpeg)

**Comment by kalinzange** [comment]
This is not a VRP Issue but yes missing textures, models, anything that impacts the clothing. Please join the discord for better support.

@JamesEU please close this
