### ISSUE TITLE
Commit broke functionality

### ISSUE THREAD

**Issue by Davidoff7776** [DunkoUK/dunko_vrp#252]
Commit `9973238a8d295859a8da2c0ae1f664973067491d` broke menu functionality. After you leave a checkpoint that opens up a menu it won't close automatically. Any version before that commit works.

**Comment by JamesEU** [comment]
https://github.com/DunkoUK/dunko_vrp/commit/c870152c72498ea574a8b1451d162bc6c949fcd7
