### ISSUE TITLE
Great to see this as a resource, but where do newbies learn?

### ISSUE THREAD

**Issue by chsims1** [DunkoUK/dunko_vrp#34]
Hi Dunko,

so for the last couple of days I have been looking into FiveM at the request of my son, who wants to run a server for his mates.  The lack of documentation makes starting from scratch a non-starter.  Came across vRP and thought yep, framework in place, but even here you either know it or don't.  Really, really pleased to see dunko_vrp on GitHub ... thought job solved, but doesn't work straight from rep and so comes down again to documentation .. quite a few errors in server startup, and I wonder if I even have the MySQL DB set up correctly. 

So four questions. (was 2 originally :))....

1. Is it usual to get a lot of error messages on server startup?

2. MySQL is running and I have a database called vRP (with appropriate references in server.cfg and vrp/cfg/base.lua), but is there an easy way to check that this is working fine with with vRP? If I look at the DB in HeidiSQL it shows there is nothing in it.

3. Do you have some links for sites with helpful info?  Where did you learn from?

4. I can't seem to find any details about how to invoke admin functions.  Hotkey list ?

And finally, when I log onto the server, I am fixed in position, no movement and sometime below ground level.

Apologies for the assault (figurative), wanting to learn more, but finding it hard to find something to read other than endless YouTube videos about how to install FXServer, rather than developing the server.

Cheers bud!

**Comment by KilobaiD** [comment]
You can come into dunko's discord into general-and-support for any further questions.
https://discord.gg/8DCMwX

And you could also watch this.

https://youtu.be/zrqF7mej-50

**Comment by chsims1** [comment]
Ty KilobaiD, I'll drop in tomorrow .. cheers
