### ISSUE TITLE
Menu freezes the game.

### ISSUE THREAD

**Issue by MomokaChan** [DunkoUK/dunko_vrp#40]
For some reason I cannot get the menu to work. When it manages to open, it freezes the game when I try to either use a function or buy something. It locks up my keyboard except for the function keys.

**Comment by adam-g-100** [comment]
+1 This is definitely an issue with the latest menu update.
Bank and Job is also not showing

**Comment by DunkoUK** [comment]
Sorry I overlooked this, both your issues are resolved.
