### ISSUE TITLE
ChopShop Race Condition

### ISSUE THREAD

**Issue by ApocDev** [DunkoUK/dunko_vrp#41]
The chop shop currently suffers from a race condition where the price to sell a vehicle cycles quickly with multiple people online, and driving due to a few factors...

1) https://github.com/DunkoUK/dunko_vrp/blob/master/vrp_chopshop/server.lua#L37 The "setVehPrice" event is being broadcast to the entire server, instead of the client actually requesting the "getVehPrice", which means other clients (while driving) are setting the price of your vehicle, when they shouldn't.

2) The client thread is constantly requesting the current price (when it should only be requesting while near the actual marker), causing unnecessary network strain, and CPU hogging.

Simple fix; change "-1" to "source" and at least the vehicle sell price craziness goes away. Other modifications are needed to lessen the strain on the CPU and network from polling these events every single chance it gets while the player is in a vehicle.

**Comment by DunkoUK** [comment]
Thanks I'll look into this, I don't check Git often as you can see, Discord is the best way to get hold of me.
