### ISSUE TITLE
I'm not sure.

### ISSUE THREAD

**Issue by Toxikflea** [DunkoUK/dunko_vrp#42]
https://gyazo.com/2992dd889668d7ff7b7036ba1a719bec

Is anyone able to tel me what this means?

**Comment by Mechman007** [comment]
You are missing your MySQL, eather you did not start the mysql server. ORe you are missing the right info in server.cfg ore vrp/cfg/base.lua

**Comment by Toxikflea** [comment]
Thanks I looked back and noticed the connection info was wrong. If you can please mark this as closed.

**Comment by justinfarmer14** [comment]
@DunkoUK Mark this as closed
