### ISSUE TITLE
The download seems to be missing a file.

### ISSUE THREAD

**Issue by Toxikflea** [DunkoUK/dunko_vrp#43]
https://gyazo.com/6aa628ddd3a610e6a6b725d4b2798cb0

**Comment by Mechman007** [comment]
HTat is not file missing, that is you missing to connect the server to MySQL server. Ore change hte MySQL info in server.cfg ore vrp/cfg/base.lua

**Comment by Toxikflea** [comment]
Alright, could you please make your errors a little easier to understand.
