### ISSUE TITLE
Upgrading a car

### ISSUE THREAD

**Issue by Supraimas** [DunkoUK/dunko_vrp#45]
Hi, I don't know is it a problem or not, but when i upgrade custom car for example i change a color and then when i store it and i take again out it goes in main color that i bought and all upgrades are removed also.

Sorry for bad english

**Comment by Mechman007** [comment]
Yes, that is not a fault ore a bug. The garages that is in the pack is not made for saving your tuning, mods paint and so on. Also there for the stuff in the lscustom is free.
You need to use another garages if you want to use saving. But sicens this is not in the pack, its not supported by dunko support team.
