### ISSUE TITLE
Wont save 

### ISSUE THREAD

**Issue by stephen1990** [DunkoUK/dunko_vrp#53]
tattoos don’t save
Aswell as customisable cars once you’ve customised them then log off then log back on they are normal again

**Comment by DoubleRepo** [comment]
Not a part of the Dunko Pack, those are different resources that are not inside DUNKO.

**Comment by stephen1990** [comment]
yes they are as it game with pack

**Comment by DoubleRepo** [comment]
As the resources you are talking about are not inside the Dunko vRP pack, it is not a issue with something inside Dunko vRP.

**Comment by stephen1990** [comment]
it came with his pack i have not dsone nothink else

**Comment by DoubleRepo** [comment]
Dude, the garage you want is a DIFFERENT resource, its not INSIDE dunko vRP and neither is the vrp_tattoo resource.

**Comment by justinfarmer14** [comment]
Hello,

So at this time I’ll bro looking into the tattoo and cars can be looked into but for the love of god can’t both of you fucking cunts just message each other than flooding my god damn discord you fucking cunts


Thanks,

Buk Changlo
Senior Manangement Team/Project Supervisor

**Comment by DunkoUK** [comment]
1) LS Customs doesn't save, it's not a bug or an issue, it's literally just not coded in to do so, yet.

2) Where are you attempting to put tattoos on?

**Comment by stephen1990** [comment]
its what my users are saying

**Comment by DunkoUK** [comment]
What? I asked a question ?

**Comment by stephen1990** [comment]
its just cars wont save updates

**Comment by Mechman007** [comment]
@stephen1990 Its not made to save, that is not how the garages system is coded. If you want it to save you need to code htat, ore sure a garages system that support this.
