### ISSUE TITLE
problem with the name job

### ISSUE THREAD

**Issue by MAX3D11** [DunkoUK/dunko_vrp#55]
Hi,

first i have to think you for everything all this project free :) You are the best

secondly , when i change the name of jobs in  
vrp/cfg/groups.lua  

to my language " Arabic " 

its changed without any issue  

after i login to the game and choose the job everything is good

but after i logout and login again or restart the server 

that job i chosen its disappears and i have to take my job again every time 

when i log in or restart the server 

i hope you help me with this issue 

i'll be thankful ,, and i'm sorry for my bad English :)

**Comment by oMarkez** [comment]
If you lose your job everytime you relog, that would be because your database is not saving it. Check your console for any errors, if there are none then check your database and make sure you have a table called "vrp_user_data", if you do not have that table then you should make sure you have the latest version of Dunkos vRP.

**Comment by MAX3D11** [comment]
i lose my job just only if change it to Arabic 
if its english i lose it

everything work perfectly just i have this issue when i translate it to Arabic

**Comment by oMarkez** [comment]
Then you are doing something wrong with your translation, or the database does not support arabic symbols, not sure. 

Did you check your console for errors?

**Comment by MAX3D11** [comment]
yes there is no error 

can you tell me how can i support arabic symbols in database if is that ok for you :)

**Comment by MAX3D11** [comment]
Thank you soo much 

my issue have been solved 

by supporting arabic in database 
you are my hero

**Comment by oMarkez** [comment]
No problem mate, sorry I didn't respond, just had to make some lunch.
