### ISSUE TITLE
[Error] I have a error trying to join in my server 

### ISSUE THREAD

**Issue by ShutAP1337** [DunkoUK/dunko_vrp#56]
My server starts fine, but when i try to join give me this error in the console:

![sem titulo](https://user-images.githubusercontent.com/41197101/42694876-aa9ace98-86ab-11e8-9858-4cfc20711d77.png)

and this in the game:

![sem titulo1](https://user-images.githubusercontent.com/41197101/42694885-b0c96aea-86ab-11e8-95a6-8278cd49890b.png)

I would appreciate a solution. Thank you

**Comment by DunkoUK** [comment]
You've not set up your database details correctly in the top of server.cfg and/or vrp/cfg/base.lua

Follow the video on my Discord if you're struggling mate.

**Comment by ShutAP1337** [comment]
I put correctly but my database is on a external cpanel/phpmyadmin and i cant create a database without a prefix (slashcom_database) i created with vrpfx and it doenst worked (slashcom_vrpfx) and how can i contact you? Per discord?

**Comment by BruhTrailSupport** [comment]
This issue has been solved by me (Bruh in Support Trail). 
We wish you and your server the best!

**Comment by ShutAP1337** [comment]
problem solved by bruh ty :D
