### ISSUE TITLE
Problem with missions spanish translation

### ISSUE THREAD

**Issue by diseva1** [DunkoUK/dunko_vrp#57]
In the spanish file located here: https://github.com/DunkoUK/dunko_vrp/tree/master/vrp_basic_mission/cfg/lang 

The first line it is upside down

**Comment by DunkoUK** [comment]
What do you mean by upside down lol? I didn't do any of the translations, if there are issues, feel free to submit a pull request fixing it.

**Comment by justinfarmer14** [comment]
Hello,
Do to the regard of inactivity we will mark this issue as ongoing and have a native translator finish this issue ASAP.

Theanks,
Buk
Senior Management
