### ISSUE TITLE
[vRP] Identification error

### ISSUE THREAD

**Issue by TheMrkoia** [DunkoUK/dunko_vrp#58]
Hi, I just installed DunkoRP on my PC and when I try to join the server by Local Host it shows up: [vRP] Identification error
I looked on the internet but nothing helped
![c96afb5da9bfceef800177fa49c5a183](https://user-images.githubusercontent.com/7188166/44658140-8fd64280-a9f7-11e8-9b39-77a5db9369c5.png)

**Comment by ElusionPDX** [comment]
database is not setup

**Comment by TheMrkoia** [comment]
Could you tell me how to fix that / set it up?

**Comment by ElusionPDX** [comment]
easiest way is to install xampp "https://www.apachefriends.org/index.html"
then set you fivem server db info to localhost or 127.0.0.1 for ip
root for user
and no password
To edit you server info go to..  vrp/cfg/base.lua

**Comment by ElusionPDX** [comment]
and also set that info in your server.cfg if needed

**Comment by TheMrkoia** [comment]
@ElusionPDX Ok, I have xampp installed, Where do I find my db info?

**Comment by justinfarmer14** [comment]
If you would like to join our discord we can address the issue at hand

**Comment by TheMrkoia** [comment]
@justinfarmer14 If you could help then sure. But I can't talk right now so typing only.

**Comment by TheMrkoia** [comment]
@ElusionPDX  I have this but still doesn't work
  host = "localhost", -- database ip (default is local)
  database = "vrpfx",   -- name of database
  user = "root",    --  database username
  password = ""   -- password of your database

**Comment by ElusionPDX** [comment]
You will need to add the db to SQL. So you will need a SQL client like navicat to open the SQL server.

**Comment by ElusionPDX** [comment]
I'm mobile now so replys will be slower.

**Comment by TheMrkoia** [comment]
@ElusionPDX When I have navicat downloaded what next?

**Comment by ElusionPDX** [comment]
Install it then add a connection. Ip will be localhost or 127.0.0.1
User will be root
Password will be blank.
Test
If OK double click the just added SQL server then right click it and add database. Make the name match all the configs. So all must say vrpfx if that's what you want to use

**Comment by TheMrkoia** [comment]
What do I put here and here?

![5692af7111013f2d77414e5ddcbb5bf7](https://user-images.githubusercontent.com/7188166/44660910-ff9cfb00-aa00-11e8-9978-7bb779ffcae2.png)
![ceae1f3794de4e1d27b01a83fbb9e60f](https://user-images.githubusercontent.com/7188166/44660912-00359180-aa01-11e8-857c-0e235a506201.png)

**Comment by ElusionPDX** [comment]
Just put the name as vrpfx

**Comment by TheMrkoia** [comment]
In this do I put 
  host = "localhost", 
  database = "vrpfx",   
  user = "root",  
  password = ""  
?
![6f8e613e59ab43854715c2da515e8b89](https://user-images.githubusercontent.com/7188166/44661066-64f0ec00-aa01-11e8-9f7c-b827340bf5d4.png)

**Comment by ElusionPDX** [comment]
Just click ok

**Comment by TheMrkoia** [comment]
Okay, then?

**Comment by ElusionPDX** [comment]
Run the server.

**Comment by TheMrkoia** [comment]
Works! Thanks very much :D

**Comment by ElusionPDX** [comment]
Happy to help. Enjoy your new dvrp server.

**Comment by DylinKirk** [comment]
Hi, All Recent Players who join my server are fine but when a new player joins server the server crashes with vRP Error _> init_user_identity

**Comment by namehtnitsuj** [comment]
can someone help me with vRP im getting a identification error
