### ISSUE TITLE
Menu freez

### ISSUE THREAD

**Issue by TomStarsky** [DunkoUK/dunko_vrp#6]
Hi Dunko i install your great work on my Server. 
But i  hav e Bug in the Dialog. I cant close the Dialogs! 

Can you help me for fix that?

**Comment by SPJESTER** [comment]
u have to click the option again?

**Comment by DunkoUK** [comment]
Sorry I've only just got back online, has this been resolved?

**Comment by D3uxx** [comment]
No reply to this so guess it's been solved.
