### ISSUE TITLE
Identity problem

### ISSUE THREAD

**Issue by MarkoEscobar** [DunkoUK/dunko_vrp#63]
I got the problem with identity. When i join in server and i look on scoreboard my name is like change me like normal. But when i try to change identity i get the error in console http://prntscr.com/l8us49 and in game scoreboard shows http://prntscr.com/l8uukm also its shows this on fresh files no editing or something SORRY FOR BAD ENGLISH

**Comment by justinfarmer14** [comment]
Hello, 
I'm replying to inform you we have pushed a hotfix to address this issue. Thank you for your patience in this matter.

Sincerely,
Buk
Senior Management 
 U.S. Division
