### ISSUE TITLE
Identification error

### ISSUE THREAD

**Issue by JOLIEKo** [DunkoUK/dunko_vrp#66]
Hey mate,
Having a major issue with the 'Identity' feature of this download.

The issue we're having is after a couple times connecting to the server or even straight away.
A lot of users are unable to connect with the prompt of "vRP Identification error" and they are completely unable to join, until I remove them from the database and they basically have to restart.

Please inform me of what information you need from me and I can get that sorted out for you asap.

Thank you,
Joliek,

**Comment by jonathanvejrgang** [comment]
I am having the same error please help
