### ISSUE TITLE
basic_garage problem

### ISSUE THREAD

**Issue by hartturmch** [DunkoUK/dunko_vrp#69]
i just updated my basic_garage with that 21h ago.
it says i have a problem in line 405 just after )
i didnt manage to solve this.

![image](https://user-images.githubusercontent.com/13525417/47612381-3ec6e700-da58-11e8-8ab2-35d4c38e6b74.png)

when i use the old one this error does not happen

**Comment by Navvv** [comment]
I updated to the latest commited basic_garage.lua too and getting the same error in my console. 

![error](https://user-images.githubusercontent.com/44418976/47617381-9f890a80-dabe-11e8-92c7-02183bd4055b.png)

**Comment by spikytarr** [comment]
Hi Guys. We have picked up on the issue and we are working on it, we hope to fix it ASAP

Spiky
Dunko Support Team

**Comment by spikytarr** [comment]
Issue is Fixed. Please look at the latest edit

**Comment by spikytarr** [comment]
Issue Closed!
