### ISSUE TITLE
Vrp split/ghost server

### ISSUE THREAD

**Issue by cranberrycurt** [DunkoUK/dunko_vrp#73]
First off great mod i appreciate the time effort put into this script. The issue i am having is when i have vrp on in my server guys get stuck in solo sessions and when i turn off vrp everyone is able to get into my server. So we have had vrp for almost a year and never had that problem. FiveM had an update last week and now its a problem. I dont know if i edit something wrong i vrp ,but when i put in back up files  of vrp i still get the issue.

**Comment by DunkoUK** [comment]
It's more than likely a fivem issue mate, try downgrading and see if the issue goes away

**Comment by justinfarmer14** [comment]
Closed due to lack of reply
