### ISSUE TITLE
Death issue.

### ISSUE THREAD

**Issue by hnomkeng** [DunkoUK/dunko_vrp#8]
Git hash : 4ff3d26
Issue : Dead and then come back to life after re-join.

**Comment by vrpResources** [comment]
It's a way to combat well.. combat loggers. When you dc when you're dead you'll die shortly after rejoin.

**Comment by hnomkeng** [comment]
I think it isn't roleplay mode.

**Comment by hnomkeng** [comment]
@DunkoUK What closed ?

**Comment by DunkoUK** [comment]
Yeah you've had your answer mate

**Comment by hnomkeng** [comment]
@DunkoUK OK, Thank you.
