### ISSUE TITLE
Player Spawn but not in the server

### ISSUE THREAD

**Issue by bgiorgio0506** [DunkoUK/dunko_vrp#98]
Hi I am running a Dunko vRP server with the rocademption queue but we are having problems with users that after the spawn in the Main Hospital they have no money HUD , Hunger &Thirst full , Their ID is not in the player list . Server cfg :
sv_authMaxVariance 1
sv_authMinTrust 5

No essesiatialmode installed

Thanks in advance for the help

**Comment by Mechman007** [comment]
Can see you ask the sam question on discord. case will be closed here
